import { IFeature } from "../components/Features/Features"
import { PricingPlanType } from "../components/Pricing/Pricing"
import {
  FIRST_FEATURE_DESCRIPTION,
  FIRST_FEATURE_TITLE,
  FIRST_NAVIGATION_SECTION,
  FIRST_PRICING_PLAN_FEATURES,
  FIRST_PRICING_PLAN_PRICE,
  FIRST_PRICING_PLAN_TITLE,
  FIRST_TESTIMONY_NAME,
  FIRST_TESTIMONY_QUOTE,
  FOURTH_FEATURE_DESCRIPTION,
  FOURTH_FEATURE_TITLE,
  FOURTH_NAVIGATION_SECTION,
  HE_FIRST_FEATURE_DESCRIPTION,
  HE_FIRST_FEATURE_TITLE,
  HE_FIRST_NAVIGATION_SECTION,
  HE_FIRST_PRICING_PLAN_FEATURES,
  HE_FIRST_PRICING_PLAN_PRICE,
  HE_FIRST_PRICING_PLAN_TITLE,
  HE_FIRST_TESTIMONY_NAME,
  HE_FIRST_TESTIMONY_QUOTE,
  HE_FOURTH_FEATURE_DESCRIPTION,
  HE_FOURTH_FEATURE_TITLE,
  HE_FOURTH_NAVIGATION_SECTION,
  HE_SECOND_FEATURE_DESCRIPTION,
  HE_SECOND_FEATURE_TITLE,
  HE_SECOND_NAVIGATION_SECTION,
  HE_SECOND_PRICING_PLAN_FEATURES,
  HE_SECOND_PRICING_PLAN_PRICE,
  HE_SECOND_PRICING_PLAN_TITLE,
  HE_SECOND_TESTIMONY_NAME,
  HE_SECOND_TESTIMONY_QUOTE,
  HE_THIRD_FEATURE_DESCRIPTION,
  HE_THIRD_FEATURE_TITLE,
  HE_THIRD_NAVIGATION_SECTION,
  HE_THIRD_PRICING_PLAN_FEATURES,
  HE_THIRD_PRICING_PLAN_PRICE,
  HE_THIRD_PRICING_PLAN_TITLE,
  SECOND_FEATURE_DESCRIPTION,
  SECOND_FEATURE_TITLE,
  SECOND_NAVIGATION_SECTION,
  SECOND_PRICING_PLAN_FEATURES,
  SECOND_PRICING_PLAN_PRICE,
  SECOND_PRICING_PLAN_TITLE,
  SECOND_TESTIMONY_NAME,
  SECOND_TESTIMONY_QUOTE,
  THIRD_FEATURE_DESCRIPTION,
  THIRD_FEATURE_TITLE,
  THIRD_NAVIGATION_SECTION,
  THIRD_PRICING_PLAN_FEATURES,
  THIRD_PRICING_PLAN_PRICE,
  THIRD_PRICING_PLAN_TITLE
} from "./strings"

import Compatibility from "../assets/images/compatibility-64.png"
import Access from "../assets/images/access-80.png"
import Design from "../assets/images/design-80.png"
import Lightning from "../assets/images/lightning-bolt-40.png"

import { TestimonyType } from "../components/Testimonials/Testimonials"

export const NAVIGATION_SECTIONS = [
  FIRST_NAVIGATION_SECTION,
  SECOND_NAVIGATION_SECTION,
  THIRD_NAVIGATION_SECTION,
  FOURTH_NAVIGATION_SECTION
]

export const HE_NAVIGATION_SECTIONS = [
  HE_FIRST_NAVIGATION_SECTION,
  HE_SECOND_NAVIGATION_SECTION,
  HE_THIRD_NAVIGATION_SECTION,
  HE_FOURTH_NAVIGATION_SECTION
]

export const FIRST_PRICING_PLAN: PricingPlanType = {
  features: FIRST_PRICING_PLAN_FEATURES,
  price: FIRST_PRICING_PLAN_PRICE,
  title: FIRST_PRICING_PLAN_TITLE
}

export const SECOND_PRICING_PLAN: PricingPlanType = {
  features: SECOND_PRICING_PLAN_FEATURES,
  price: SECOND_PRICING_PLAN_PRICE,
  title: SECOND_PRICING_PLAN_TITLE
}

export const THIRD_PRICING_PLAN: PricingPlanType = {
  features: THIRD_PRICING_PLAN_FEATURES,
  price: THIRD_PRICING_PLAN_PRICE,
  title: THIRD_PRICING_PLAN_TITLE
}

export const HE_FIRST_PRICING_PLAN: PricingPlanType = {
  features: HE_FIRST_PRICING_PLAN_FEATURES,
  price: HE_FIRST_PRICING_PLAN_PRICE,
  title: HE_FIRST_PRICING_PLAN_TITLE
}

export const HE_SECOND_PRICING_PLAN: PricingPlanType = {
  features: HE_SECOND_PRICING_PLAN_FEATURES,
  price: HE_SECOND_PRICING_PLAN_PRICE,
  title: HE_SECOND_PRICING_PLAN_TITLE
}

export const HE_THIRD_PRICING_PLAN: PricingPlanType = {
  features: HE_THIRD_PRICING_PLAN_FEATURES,
  price: HE_THIRD_PRICING_PLAN_PRICE,
  title: HE_THIRD_PRICING_PLAN_TITLE
}

export const PRICING_PLANS: PricingPlanType[] = [
  FIRST_PRICING_PLAN,
  SECOND_PRICING_PLAN,
  THIRD_PRICING_PLAN
]

export const HE_PRICING_PLANS: PricingPlanType[] = [
  HE_FIRST_PRICING_PLAN,
  HE_SECOND_PRICING_PLAN,
  HE_THIRD_PRICING_PLAN
]

export const FIRST_FEATURE: IFeature = {
  icon: Design,
  description: FIRST_FEATURE_DESCRIPTION,
  title: FIRST_FEATURE_TITLE
}
export const SECOND_FEATURE: IFeature = {
  icon: Lightning,
  description: SECOND_FEATURE_DESCRIPTION,
  title: SECOND_FEATURE_TITLE
}
export const THIRD_FEATURE: IFeature = {
  icon: Access,
  description: THIRD_FEATURE_DESCRIPTION,
  title: THIRD_FEATURE_TITLE
}
export const FOURTH_FEATURE: IFeature = {
  icon: Compatibility,
  description: FOURTH_FEATURE_DESCRIPTION,
  title: FOURTH_FEATURE_TITLE
}

export const HE_FIRST_FEATURE: IFeature = {
  icon: Design,
  description: HE_FIRST_FEATURE_DESCRIPTION,
  title: HE_FIRST_FEATURE_TITLE
}
export const HE_SECOND_FEATURE: IFeature = {
  icon: Lightning,
  description: HE_SECOND_FEATURE_DESCRIPTION,
  title: HE_SECOND_FEATURE_TITLE
}
export const HE_THIRD_FEATURE: IFeature = {
  icon: Access,
  description: HE_THIRD_FEATURE_DESCRIPTION,
  title: HE_THIRD_FEATURE_TITLE
}
export const HE_FOURTH_FEATURE: IFeature = {
  icon: Compatibility,
  description: HE_FOURTH_FEATURE_DESCRIPTION,
  title: HE_FOURTH_FEATURE_TITLE
}

export const FEATURES: IFeature[] = [
  FIRST_FEATURE,
  SECOND_FEATURE,
  THIRD_FEATURE,
  FOURTH_FEATURE
]

export const HE_FEATURES: IFeature[] = [
  HE_FIRST_FEATURE,
  HE_SECOND_FEATURE,
  HE_THIRD_FEATURE,
  HE_FOURTH_FEATURE
]
export const FIRST_TESTIMONY_RATING = 5
export const SECOND_TESTIMONY_RATING = 4
export const HE_FIRST_TESTIMONY_RATING = 5
export const HE_SECOND_TESTIMONY_RATING = 4

export const FIRST_TESTIMONY: TestimonyType = {
  clientPhoto: "",
  name: FIRST_TESTIMONY_NAME,
  quote: FIRST_TESTIMONY_QUOTE,
  rating: FIRST_TESTIMONY_RATING
}

export const SECOND_TESTIMONY: TestimonyType = {
  clientPhoto: "",
  name: SECOND_TESTIMONY_NAME,
  quote: SECOND_TESTIMONY_QUOTE,
  rating: SECOND_TESTIMONY_RATING
}

export const HE_FIRST_TESTIMONY: TestimonyType = {
  clientPhoto: "",
  name: HE_FIRST_TESTIMONY_NAME,
  quote: HE_FIRST_TESTIMONY_QUOTE,
  rating: HE_FIRST_TESTIMONY_RATING
}

export const HE_SECOND_TESTIMONY: TestimonyType = {
  clientPhoto: "",
  name: HE_SECOND_TESTIMONY_NAME,
  quote: HE_SECOND_TESTIMONY_QUOTE,
  rating: HE_SECOND_TESTIMONY_RATING
}

export const TESTIMONIALS: TestimonyType[] = [FIRST_TESTIMONY, SECOND_TESTIMONY]
export const HE_TESTIMONIALS: TestimonyType[] = [
  HE_FIRST_TESTIMONY,
  HE_SECOND_TESTIMONY
]

export const TERMS_CONDITIONS_LINK = ""
export const HE_TERMS_CONDITIONS_LINK = ""
